# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(766, 482)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 340, 210, 17))
        self.label_2.setObjectName("label_2")
        self.Start_button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_button.setGeometry(QtCore.QRect(250, 360, 261, 61))
        self.Start_button.setObjectName("Start_button")
        self.OpenFile_button = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFile_button.setGeometry(QtCore.QRect(630, 440, 121, 31))
        self.OpenFile_button.setObjectName("OpenFile_button")
        self.Name_label = QtWidgets.QLabel(self.centralwidget)
        self.Name_label.setGeometry(QtCore.QRect(210, 130, 351, 111))
        self.Name_label.setMinimumSize(QtCore.QSize(351, 111))
        self.Name_label.setMaximumSize(QtCore.QSize(351, 111))
        self.Name_label.setObjectName("Name_label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "随机点名"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">随机点名-V2.1.1 </span><span style=\" font-size:11pt; font-weight:600; font-style:italic;\">(编译日期 2024.11.3)</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">点击“开始”按钮开始随机点名</span></p></body></html>"))
        self.Start_button.setText(_translate("MainWindow", "开始"))
        self.OpenFile_button.setText(_translate("MainWindow", "打开随机点名文件"))
        self.Name_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
